TRUNCATE entries;
INSERT INTO entries
(day, date, month, content, note, imageNote, imageURL, abridged)
VALUES
('Tuesday', '26th', 'January', 'Enlisted and attested for Royal Marines Field Artillery at Liverpool.', 'Before he set sail for Gallipoli Bampa was transferred to the Field Ambulance Section of the Royal Naval Division (RND) on 20th  February.', 'Bampa''s Diary (Tap to zoom)', 'diary.jpg', true),
('Wednesday', '27th', 'January', 'Left Liverpool for Crystal Palace, London.', null, null, null, true),
('Thursday', '28th', 'January', 'Inoculated for first time, received kit and uniform.  Stand easy.', null, null, null, true),
('Friday', '29th', 'January', 'Stand easy.', null, null, null, false),
('Saturday', '30th', 'January', 'Went to London for evening.  Received 5 shilling pay.', null, null, null, true),
('Sunday', '31st', 'January', 'Went to Wesley Church.', null, null, null, false),
('Tuesday', '2nd', 'February', 'Orderly.', null, null, null, false),
('Wednesday', '3rd', 'February', 'Orderly.', null, null, null, false),
('Thursday', '4th', 'February', 'Paraded for first squad drill under Staff Sgt Williams.', null, null, null, true),
('Friday', '5th', 'February', 'Route march 12 miles.', null, null, null, false),
('Saturday', '6th', 'February', 'Received 10 shilling pay. Went to London and saw Houses of Parliament and Westminster Abbey.  Dickens anniversary.', null, null, null, true),
('Sunday', '7th', 'February', 'Went to Congregational Church.', null, null, null, false),
('Monday', '8th', 'February', 'Placed in A section for physical drill etc.', null, null, null, false),
('Tuesday', '9th', 'February', 'Inoculated for second time 3 o’clock.  Stand easy.', null, null, null, false),
('Wednesday', '10th', 'February', 'Stand easy.', null, null, null, false),
('Thursday', '11th', 'February', 'Stand easy.', null, null, null, false),
('Friday', '12th', 'February', 'Route march 18 miles.', null, null, null, false),
('Saturday', '13th', 'February', 'Received 10 shillings pay.  Went to London saw Tower of London, Tower Bridge etc.', null, null, null, false),
('Sunday', '14th', 'February', 'Congregational Church.', null, null, null, false),
('Monday', '15th', 'February', 'Parades and drills.', null, null, null, false),
('Tuesday', '16th', 'February', 'Orderly.', null, null, null, false),
('Wednesday', '17th', 'February', 'Parades and drills.', null, null, null, false),
('Thursday', '18th', 'February', 'Parades and drills.', null, null, null, false),
('Friday', '19th', 'February', 'Route march and got drenched – Croydon.', null, null, null, true),
('Saturday', '20th', 'February', 'Received 10 shillings pay. Received another uniform and put in C section 3rd Field Ambulance Bearer Sub-Division (Royal Naval Division).  Got orders for Blandford for Monday.', 'The most unconventional of all the forces assigned to fight at Gallipoli was the RND, a strange combination of barely trained troops with next to no artillery provision.  It had been formed by Churchill as a useful home for the 20,000-30,000 Royal Navy Reservists and eager new recruits who were excess to the fleet’s immediate requirements in 1914.', null, null, true),
('Sunday', '21st', 'February', 'Kit inspection.', null, null, null, false),
('Monday', '22nd', 'February', 'Left Crystal Palace for Blandford arrived at camp 5.30 knee deep in mud and water.', null, null, null, true),
('Tuesday', '23rd', 'February', 'Inspected by Fleet surgeon. Making roads and mudlarking in general.', null, null, null, false),
('Wednesday', '24th', 'February', 'Freezing very * and a light snowfall.', null, null, null, false),
('Thursday', '25th', 'February', 'The Marines reviewed by the King and Winston Churchill. Received war kit.', null, null, null, false),
('Friday', '26th', 'February', 'Received for pay 5 shillings. Received a pair of socks from Lady Jellicoe. Bought pants. On guard at the station and stores all night.', 'Lady Jellicoe was wife of Admiral Sir John Jellicoe commander of the Grand Fleet.', null, null, true),
('Sunday', '28th', 'February', 'Reveille 3.00am. Left Blandford 5.00am for march to Shillingstone 10 miles and boarded train for Avonmouth docks and embarked on HM troopship Somali. 1st and 2nd Engineers and * cyclist scouts on board.', null, 'Embarking at Avonmouth', 'avonmouth.jpg', true),
('Monday', '1st', 'March', 'Transferred from the Somali to the Franconia. Sailed Monday night 7.30. Nelson and Drake battalions (RND) on board.', null, null, null, false),
('Tuesday', '2nd', 'March', 'Morning - no land in sight.  Evening entered Bay of Biscay.', null, null, null, false),
('Wednesday', '3rd', 'March', 'Morning - sailing through Bay of Biscay. Night – passed the Bay off the coast of Spain. Lifeboat practice no 12 boat on B boat deck.', null, null, null, true),
('Thursday', '4th', 'March', 'Travelled over 1000 miles still off the coast of Spain. Physical drill and rifle instruction. No land in sight yet.', null, null, null, true),
('Friday', '5th', 'March', 'Passed Gibralter during the night. Sailing down the Mediteranean. Night – lighthouse sighted off the coast of Africa. Franconia heading for Malta.', null, null, null, true),
('Saturday', '6th', 'March', 'Morning - first sighted land Devil’s Island, French convict settlement off the coast of Algeria. In sight of the African coast all day, very hot.', null, null, null, true),
('Sunday', '7th', 'March', 'Reached Malta about noon, anchored out all night.', null, null, null, false),
('Monday', '8th', 'March', 'Entered Valetta harbour next to coal ship: part of French navy here. Very hot. First to reach harbour.', null, 'Valetta harbour, Malta', 'malta.jpg', true),
('Tuesday', '9th', 'March', 'Evening – left the harbour of Valetta, Malta and started on our voyage again. First to leave the harbour.', null, null, null, false),
('Wednesday', '10th', 'March', 'Sports held on board the Franconia. Had my head cropped close.', null, null, null, true),
('Thursday', '11th', 'March', 'Sports finals. Sailing through the Grecian archipelago going slowly.', null, null, null, false),
('Friday', '12th', 'March', 'Entered Lemnos Bay, our naval base. British, French and Russian warships here. Thousands of troops camped on Lemnos Island. Received identity disc. Australians.', 'Lemnos is a Greek island South West of Gallipoli.', null, null, true),
('Saturday', '13th', 'March', 'Received a sub of pay 5 shillings. Transferred back to the Somali. Still in Limnos Bay.', null, null, null, false),
('Sunday', '14th', 'March', 'German tramp ship in Lemnos Bay as * * damaged.', null, null, null, false),
('Monday', '15th', 'March', 'Still in Limnos Bay. First shower of rain. *** transport of French army.', null, null, null, false),
('Tuesday', '16th', 'March', 'A little rain. Selected as crew to one of the lifeboats went for a row on the bay.', null, null, null, false),
('Wednesday', '17th', 'March', 'Very hot.', null, null, null, false),
('Thursday', '18th', 'March', 'Very hot. Intended route march on Lemnos Island stopped on account of the Somali getting orders to sail. The Somali left Lemnos at 6.15pm (don’t know the destination).', null, null, null, false),
('Friday', '19th', 'March', 'Morning - reached the Dardanelles about 2am but had to return to Lemnos Bay. 2 British and 1 French ship sunk. Arrived back at Lemnos in the evening.', 'The three sunken ships all hit a line of mines which had been laid by the Turks parallel to the Dardanelles Straits coast rather than at right angles to it as with the other mines. In addition heavy bombing from the forts guarding the entrance to the Straits had severely damaged three other ships leaving only nine still capable of action.', null, null, true),
('Saturday', '20th', 'March', 'Blowing a gale and one of our pinnaces sunk.', null, null, null, false),
('Sunday', '21st', 'March', 'No * boat with 9 men missing. Blowing a gale.', null, null, null, true),
('Monday', '22nd', 'March', 'Noon – missing crew returned after being picked up by survivors of Ocean and Invincible.', 'Two of the boats sunk during 18th March naval attack on the Narrows. The latter ship is incorrect it should be the Irresistible.', null, null, true),
('Tuesday', '23rd', 'March', 'Got a job painting the numbers etc on lifeboat for troop officer. Concert in our sleeping quarters, Surgeon Anderson *.', null, null, null, true),
('Wednesday', '24th', 'March', 'Printed Surgeon Taylor * *. Vaccinated. Held a service in our sleeping quarters led and conducted by ourselves.', null, null, null, false),
('Thursday', '25th', 'March', 'The Somali left Lemnos Bay at 9.00am.', null, null, null, false),
('Friday', '26th', 'March', 'Morning - sailing through the Grecian Archipelago. Afternoon – passed island of Cyprus. Sports on board the Somali.', null, null, null, false),
('Saturday', '27th', 'March', 'Morning – arrived at Alexandria, Egypt. Very hot. Egyptians very quaint dressed in robes. Left Alexandria at 4.00pm.', null, 'Egyptian street', 'egypt-street.jpg', true),
('Sunday', '28th', 'March', 'Arrived at Port Said at 8.00am and a French man of war played Tipperary as we sailed in.', null, 'Entrance to Suez Canal at Port Said', 'port-said.jpg', true),
('Monday', '29th', 'March', 'Preparing to land with our baggage etc. Boiling hot. One of the Anson lads murdered by an Arab.', 'Anson was an RND battalion.', null, null, true),
('Tuesday', '30th', 'March', 'Received pay of 10 shillings and landed. Camped on the sea shore with the Gurkhas only 12 miles from the trenches.', null, null, null, true),
('Wednesday', '31st', 'March', 'Got leave to go into town. Not to buy anything from the Arabs or anyone on the street. Not to eat or buy any native drinks.', null, null, null, true),
('Thursday', '1st', 'April', 'Expedition marched up the Suez to assist the Australians against the Turks. Enemy sighted but did not engage.', 'A German led Turk army had made a failed attack on the Suez Canal between 26th January and 4th February.', null, null, true),
('Friday', '2nd', 'April', 'Bivouacking behind the trenches waiting. Returned waiting.', null, null, null, false),
('Saturday', '3rd', 'April', 'Review of troops in Port Said, Egypt. Packing etc ready for leaving Port Said.', null, null, null, false),
('Monday', '5th', 'April', 'At 10.00am this morning a heat * * over Port Said and were swarmed with a plague of locusts.', null, null, null, true),
('Thursday', '8th', 'April', 'Attended a service held in one of the rooms of the British and Foreign Bible Society. Received letter from Margaret.', 'Margaret was Bampa''s girlfriend at this time, they later married in 15th June 1921', null, null, true),
('Friday', '9th', 'April', 'Received orders to parade in full marching order to embark on the Somali leaving those behind singing ‘God be with you until we meet again’. Embarked about 5.30pm.', null, null, null, false),
('Saturday', '10th', 'April', 'Left the harbour of Port Said *am on the Somali 1st and 3rd Field Artillery and Royal Marines Artillery on board. Afternoon – no land in sight.', null, null, null, true),
('Sunday', '11th', 'April', 'Lost our lighter carrying our water supply for the field.', null, null, null, false),
('Monday', '12th', 'April', 'Sailing through the Grecian Archipelago again. Received pay 4s 6d.', null, null, null, false),
('Tuesday', '13th', 'April', 'Arrived at Lemnos about 12 noon.', null, null, null, false),
('Wednesday', '14th', 'April', 'Still in the Bay of Lemnos. Battleships of all descriptions. Destroyers, submarines, sea planes, transports and troop ships. British, French, Australians.', null, null, null, true),
('Thursday', '15th', 'April', 'Still in the Bay of Lemnos.', null, null, null, false),
('Friday', '16th', 'April', 'Sailed from Lemnos Bay about 6.30am without escorts. Heading for an island and at 11 o’clock when about two miles from it transports wheeled round and put on top speed back. Received SOS that Manit... torpedoed. 11.15am wheeled round to the rescue. 12.45pm 2 cruisers came up to search for the destroyer. 1 o’clock arrived at the *. 2.30pm sailed away and arrived at Skyros at 4.00pm.', null, null, null, true),
('Saturday', '17th', 'April', 'Landed at Skyros for a sham fight in the hills for a practice. Hills very rocky and covered with * and prickly bushes.', null, null, null, false),
('Sunday', '18th', 'April', 'Route march.', null, null, null, false),
('Monday', '19th', 'April', 'Manoeuvres again.', null, null, null, false),
('Tuesday', '20th', 'April', 'Manoeuvres.', null, null, null, false),
('Wednesday', '21st', 'April', 'Received tin of cigarettes. 3 Turkish spies brought in in a smack carrying wireless taken prisoners by cruiser.', 'A Smack is a small boat. A wireless is an old term for a radio.', null, null, true),
('Thursday', '22nd', 'April', 'RMA gunner * * on the Somali and condemned to pack drill and to be tied to a gun for 28 days for striking a sergeant major.', 'Pack drill was a punishment given to soldiers in the British Army, requiring them to undertake drill (exercise) in full uniform and carrying a heavy pack.', null, null, true),
('Friday', '23rd', 'April', 'Received pay 5 shillings.', 'On this day 27 year old Sub Lieutenant Rupert Brooke one of the famous World War 1 poets who was also in the Royal Naval Division and taking part in the same mock battles on Skyros died from severe blood poisoning apparently caused by an insect bite on his lip, probably from a mosquito in Port Said. He was buried in an olive grove high on the side of the island. ''If I should die think only this of me; That theres some corner of a foreign field, That is forever England.'' (The Soldier)', null, null, true),
('Saturday', '24th', 'April', 'Left Skyros about 6.00am. Sailing throughout the Aegean. Served with second Iron Ration. Received tin of tobacco.', 'The ''Iron Ration'' was an emergency ration of preserved meat, cheese, biscuit, tea, sugar and salt to be used in the event of being cut off from regular food supplies.', null, null, true),
('Sunday', '25th', 'April', 'Arrived at Gulf of Saros early morning.', 'Saros is off the West side of the Gallipoli Pensinsula, North of Suvla Bay.', null, null, true),
('Monday', '26th', 'April', 'Preparing to land troops. Had to look out for enemy seaplanes. Could hear the warships bombarding the forts. Left Saros for the Dardanelles about 9.00pm.', null, null, null, true),
('Tuesday', '27th', 'April', 'Arrived Dardanelles early morning at the scene of bombardment. Thousands of * landing. The * * terrible earsplitting. The warships kept up the bombardment all day at the forts and in the afternoon heard some artillery at Gaba Tepe.', 'The Anzacs had landed at Gaba Tepe on the 25th April.', 'Ruined street in Sedd-el-Bahr', 'sedd-el-bahr-street.jpg', true),
('Wednesday', '28th', 'April', 'The bombardment again resumed. Some of the RND had landed and taken up their positions against the Turks. We are standing by waiting for a minutes notice to land. Field (Ambulance) landed about *pm.', null, null, null, true),
('Thursday', '29th', 'April', 'Australians assaulting a * * 50ft – gaining ground. 4pm received orders to *. 6.00pm transferred to Grantully Castle and attached to Hood Battalion.', 'Grantully Castle - one of the troop transport ships.', null, null, true),
('Friday', '30th', 'April', 'Landed at Cape Helles at 2.00am. About 9.00 the Turks commenced to bombard our position – shrapnel and shells all around. * * town and forts * * * of Sedd-el-Bahr.', null, 'Cape Helles', 'cape-helles.jpg', true),
('Saturday', '1st', 'May', 'Bivouacking waiting orders.', null, null, null, false),
('Sunday', '2nd', 'May', 'Big battle takes place with heavy losses on both sides. 3rd Field sent in the trenches under fire. The screams and * of shells, shrapnel and bullets were terrible and we daren’t show the tops of our hats above the trenches. 5.30pm I was told to go with the Howe Battalion * * night * * all * *.', 'This was the first of three Battles of Krithia which had begun on 28th April. The period between the second and third battles of Krithia were for the most part taken up taken up with particularly gruelling trench warfare. For the British and French forces at Helles protection against the hail of shells and machine gun fire was worse than many areas on the Western Front.', 'Firing line, RND sector', 'rnd-sector.jpg', true),
('Monday', '3rd', 'May', 'Still with the Howe Battalion to take up new position with Gurkhas, Sikhs and French. 3.00pm sent from the Howe lines * messenger through the lines of * * to camp for stretcher bearers up Krithia Rd.', null, 'Firing line, RND sector', 'rnd-sector-2.jpg', true),
('Tuesday', '4th', 'May', '* * Howe * * * * shrapnel for *. 3.00am sent from Howe * rest of 3rd Field from * * * *. 10.30am * my company and * * Howe * Kereves valley * still * every day. Not had sleep for 3 days until now.', null, null, null, true),
('Wednesday', '5th', 'May', 'Still in the same camp getting used to shells and shrapnel. * first time having a wash for 4 days. Went out again to the trenches at 12.00 noon until 2.30 following *. 5 of our stretcher bearers wounded and one killed. Asquith’s son * off the field by us. Lieutenant in the Hoods.', 'Herbert Asquith was the Prime Minister of the UK from 1908 to 1916.', null, null, true),
('Thursday', '6th', 'May', '2nd Field Ambulance arrived to relieve us. Relieved of field work today. 3rd Field received a gift of 50 cigarettes and box of matches (received with welcome).', null, null, null, true),
('Friday', '7th', 'May', 'Out again right in the trenches. Another attack * the hill Achi Baba. Turks driven back. * 3rd Field wounded.', 'This was the second Battle of Krithia.', null, null, true),
('Saturday', '8th', 'May', '* out again. 5 of us sent on the Drake’s advanced trenches including myself. Relieved at 12.00 noon. 6.00pm Turks attempt to rush us to drive us back but are simply wiped out * * * * * * advance.', null, null, null, true),
('Sunday', '9th', 'May', '* out at 3.30 am to fetch wounded. Attended service in field received fags and chocs.', null, null, null, true),
('Monday', '10th', 'May', '5th, 6th and 7th battalions of the Manchester Territorials arrived.', null, null, null, false),
('Tuesday', '11th', 'May', '8th, 9th and 10th battalions of the Manchester Territorials arrived. Another attempt to take the hill, fierce fighting and heavy work.', null, null, null, true),
('Wednesday', '12th', 'May', 'Washed out of our dugouts rained heavily. RND brought from trenches for a rest and to make up the roll(?). 5th, 6th, 7th, 8th, 9th and 10th battalions of the Manchester Territorials took our places.', null, null, null, true),
('Thursday', '13th', 'May', 'Stand easy for us.  Held a service of thanksgiving.', null, null, null, false),
('Friday', '14th', 'May', 'Stand easy again. Our camp shelled heavily with shrapnel.', null, null, null, false),
('Saturday', '15th', 'May', 'Received * * * * letter * * from Margaret. Received 50 cigarettes again. More shrapnel in the camp.', null, null, null, true),
('Sunday', '16th', 'May', 'Inspected * by General Hamilton (commander of the Mediterranean Expeditionary Force) and Paris (RND General) for good work of RND.', null, null, null, false),
('Monday', '17th', 'May', 'RND went in the trenches again and made another advance. I was on night guard.', null, null, null, true),
('Tuesday', '18th', 'May', 'Out in the trenches again almost up the hill.  Sent out to the trenches to act as messenger for rest of bearers stationed on hill 200. Had to go up the Great Donga (a dry watercourse).', null, null, null, true),
('Wednesday', '19th', 'May', 'Transferring wounded from dressing station to base for a change. Received photographs of operetta characters.', null, 'Dressing Station', 'dressing-station.jpg', true),
('Thursday', '20th', 'May', 'Messenger again from the trenches to our dressing station.', null, null, null, false),
('Saturday', '22nd', 'May', 'Out bearing again in the afternoon. Our camp was shelled and one shell hit our dugout and wrecked everything, luckily we were not in it, 5 wounded. *pm sent out again and was out all night relieved on following morning.', null, 'Field Ambulance Section dugouts', 'dugouts.jpg', true),
('Sunday', '23rd', 'May', 'Attended a service in the morning held in the field.', null, null, null, false),
('Monday', '24th', 'May', '2nd Field left us for a week’s rest and 1st Field took their place after having a week’s rest.', null, null, null, false),
('Tuesday', '25th', 'May', 'In camp excused duty with my arm. Received 25 cigarettes.', null, null, null, true),
('Wednesday', '26th', 'May', 'Excused duty again. French bring up 2 big guns.', null, null, null, false),
('Thursday', '27th', 'May', 'Hawke battalion RND landed. Still excused duty. In RND camp next to ours several killed and 14 wounded with shrapnel. Fortunately we escaped.', null, null, null, false),
('Friday', '28th', 'May', 'Sent over to find Deal battalion lines for a wounded officer’s kit. Take up duty again.', null, null, null, false),
('Saturday', '29th', 'May', 'Reinforcement arrived for the medical unit from Blandford. Our side advance a trench or two on the Turks.', null, null, null, true),
('Sunday', '30th', 'May', 'Collingwood and Benbow battalions arrive.', null, null, null, false),
('Monday', '31st', 'May', 'Sergeant Roberts of C Section, 3rd Field Artillery given the DSM (Distinguished Service Medal) for the work of his section in action. Received a letter from Fred Lawson.', null, null, null, false),
('Tuesday', '1st', 'June', 'Hawkes take a big trench off the Turks. Heavy firing but have not yet taken the hill Achi Baba.', null, 'Achi Baba', 'achi-baba.jpg', true),
('Wednesday', '2nd', 'June', 'Our camp heavily shelled by Turks and one of the 3rd Field Bearers had his head blown off in his dugout.  Our left flank advance on Krithia but fear mines.', null, null, null, true),
('Thursday', '3rd', 'June', 'More shells in camp but nobody hit – also get some shrapnel.  8.00pm a night battle takes place.  A big night attack by Turks repulsed.', null, null, null, true),
('Friday', '4th', 'June', 'Morning – taking it easy.  10.30 am ordered to turn out to prepare for the bombardment.  11.00 bombardment commences. Hundreds of guns from all parts all round us. Noise of the battle is indescribable. Afternoon – battle still raging as fierce as ever and continued all day and night. Relieved about 11.30pm.', 'This is the Third Battle of Krithia.', null, null, true),
('Saturday', '5th', 'June', '2.30am called out again, still attacking. Took 4 trenches on left flank and centre. French on right flank giving way and were reinforced by Australians. Hundreds of Turkish prisoners taken including German officers and sailors.', null, 'Turkish prisoner', 'prisoner.jpg', true),
('Sunday', '6th', 'June', 'Holding our own but still getting in the wounded. Struck camp for Y Beach for a rest.', null, null, null, true),
('Monday', '7th', 'June', 'Bivouacking on Y Beach.  First days rest – plenty of bathing.', null, null, null, true),
('Tuesday', '8th', 'June', 'Second day’s rest. Making a road along the foot of the cliffs for transports.', null, null, null, true),
('Wednesday', '9th', 'June', 'Third day’s rest. Royal Scot’s arrived at Y Beach.', null, null, null, false),
('Thursday', '10th', 'June', 'Fourth day’s rest. 2 Battalions of Munsters landed at Y Beach.', null, null, null, false),
('Friday', '11th', 'June', 'Fifth day’s rest. KOSBs landed at Y Beach. Ordered to pack up to prepare to leave.', 'KOSBs - (King’s Own Scottish Borderers).', null, null, true),
('Saturday', '12th', 'June', 'Packed up and left Y Beach early morning and came to our old lines. Awaiting further orders. Our casualties up to now in the Field Ambulance RND – 6 killed, 59 wounded, 5 shattered nerves.', null, null, null, true),
('Sunday', '13th', 'June', 'Attended Holy Communion 4pm. French batteries and our camp shelled for about 3 hours by Annie from Asia and by the Turks at Achi Baba.', '''Annie from Asia'' - Turkish big gun on Asiatic side of the Dardanelles.', null, null, true),
('Monday', '14th', 'June', '1.00am left our lines in Kereves valley for Sedd el Bahr and embarked in a mine sweeper for Imbros. Arrived 5.00am. Bivouacked next to the 5/8 M/C (5th and 8th Manchesters) for a supposed reformation of RND.', 'Imbros - Island 10 miles west of Gallipoli peninsula.', null, null, true),
('Tuesday', '15th', 'June', 'Having a grand time at Imbros tasting for the first time since home eggs and real bread and a bit of bacon. Industry here is agriculture everybody working in the cornfields.', null, 'Greek shepherds', 'shepherds.jpg', true),
('Wednesday', '16th', 'June', '3rd day on Imbros.  Got some rice and goat’s milk, made an attempt at making a rice pudding in our dixies.', null, null, null, true),
('Thursday', '17th', 'June', '4th day on Imbros. More of the RND arrived here from the Peninsula. Also some Egyptian soldiers arrive here. Turkish prisoners here at work.', null, null, null, true),
('Friday', '18th', 'June', '5th day on Imbros. On guard today over our camp for 24 hours. Inspected and thanked by Sir Ian Hamilton and his staff for the good work of the RND.', null, null, null, true),
('Saturday', '19th', 'June', '6th day on Imbros. Surrey Yeomanry arrived, first cavalry in this expeditionary force. Under canvas for first time.', null, null, null, false),
('Sunday', '20th', 'June', '7th day on Imbros. Attended service.', null, null, null, false),
('Monday', '21th', 'June', '8th day on Imbros.', null, null, null, false),
('Tuesday', '22th', 'June', '9th day on Imbros.', null, null, null, false),
('Wednesday', '23th', 'June', '10th day on Imbros.', null, null, null, false),
('Thursday', '24th', 'June', '11th day on Imbros.', null, null, null, false),
('Friday', '25th', 'June', '12th day on Imbros.', null, null, null, false),
('Saturday', '26th', 'June', '13th day on Imbros.', null, null, null, false),
('Sunday', '27th', 'June', '14th day on Imbros.', null, null, null, false),
('Monday', '28th', 'June', '15th day on Imbros.', null, null, null, false),
('Tuesday', '29th', 'June', '16th day on Imbros. Heavy bombardment took place and an assault on the hill (Achi Baba) advanced about 2 miles.', 'This was the Battle of Gully Ravine 28th June – 5th July on the left flank, west of Krithia.', 'Gully Ravine with Turkish barbed wire', 'ravine-barbed-wire.jpg', true),
('Wednesday', '30th', 'June', '17th day on Imbros. Sent a letter home.', null, null, null, true),
('Thursday', '1st', 'July', '18th day on Imbros.', null, null, null, false),
('Sunday', '4th', 'July', 'Attended doctor with my leg suspected bite.', null, null, null, true),
('Monday', '5th', 'July', 'Leg inflamed and swollen. Excused duty.', null, null, null, true),
('Tuesday', '6th', 'July', 'Still excused duty.', null, null, null, false),
('Wednesday', '7th', 'July', 'Received cigarettes and chocolates from M (Margaret) and biscuits from home. Still excused duty.', null, null, null, true),
('Thursday', '8th', 'July', 'Received orders to pack up and return to peninsula. Evening embarked to go but were ordered to return. Still excused duty.', null, null, null, true),
('Friday', '9th', 'July', 'Standing by awaiting orders. Received tin of cigarettes from M. Still excused duty.', null, null, null, false),
('Saturday', '10th', 'July', 'Still standing by. Wrote to M.', null, null, null, false),
('Sunday', '11th', 'July', 'Excused duty.', null, null, null, false),
('Monday', '12th', 'July', 'Excused duty.', null, null, null, false),
('Tuesday', '13th', 'July', 'Excused duty.', null, null, null, false),
('Wednesday', '14th', 'July', 'Received orders to leave Imbros and left about 11.30pm. Replacing 2nd Field Artillery.', null, null, null, true),
('Thursday', '15th', 'July', 'Arrived at V Beach Sedd el Bahr just before daybreak and camped in dugouts left by 2nd Field Artillery.', null, null, null, true),
('Saturday', '17th', 'July', 'Returned to duty sent up in trenches for 48 hours. All the trenches named after streets. Our dressing station on corner of Oxford Street and Regent Street. Turks very quiet.', null, 'Entrance to Regent Street', 'regent-street.jpg', true),
('Sunday', '18th', 'July', 'Still up in the trenches, not many cases.', null, null, null, false),
('Monday', '19th', 'July', 'I had to stay up in the trenches for another 24 hours. Plenty of shrapnel bursting about.', null, null, null, true),
('Tuesday', '20th', 'July', '8.30am relieved and returned to camp, very tired so piped down for a sleep in my dugout.', null, null, null, true),
('Wednesday', '21st', 'July', '7.30am called out again up in the trenches for another 24 hours. Fairly busy today Turks very active.', null, null, null, true),
('Thursday', '22nd', 'July', '8.30am relieved and returned to camp.  About 5 o’clock was inoculated for cholera for first time.', null, null, null, false),
('Friday', '23rd', 'July', '6.00am called out in trenches for expected big attack by Turks.', null, null, null, true),
('Saturday', '24th', 'July', '2nd day up in the trenches, still at station corner of Oxford St. Got a good shelling from Turks who are trying to destroy our artillery control station.', null, 'Firing line, RND sector', 'firing-line.jpg', true),
('Sunday', '25th', 'July', '3rd day in the trenches no attack yet.', null, 'Periscopes on the RND firing line', 'periscopes.jpg', true),
('Monday', '26th', 'July', '4th day in trenches, last day of the Turkish Mohammedan feast, an attack from them was repulsed. Moved right up Regent St in same trench as the French (right flank) near a captured redoubt.', null, null, null, true),
('Tuesday', '27th', 'July', '5th day in trenches. Not much doing today from the enemy in front but had a hot time dodging Annie from Asia who was trying to find the trench batteries.', null, null, null, true),
('Wednesday', '28th', 'July', '6th day in trenches. Some shrapnel today but it burst to high to do much harm, biggest danger in explosive bullets. Received orders about 9.00pm to return to our camp.', null, null, null, true),
('Thursday', '29th', 'July', 'Spent nearly all day in dugout having a good sleep and rest.', null, null, null, true),
('Friday', '30th', 'July', 'Called out again about 8.00am for another spell in the trenches. Stationed at Brown House. Turks made a slight attack but a few rounds rapid drove them back.', null, 'Map showing RND Field Ambulance stations and trenches with street names', 'trench-map.jpg', true),
('Saturday', '31st', 'July', 'Returned this morning after being out for 24 hours. About 11 o’clock Turks commenced to shell around our lines and HLI (Highland Light Infantry) lines, one shell dropping just in front of our staff surgeon’s Major Kenny’s dugout fracturing his leg badly and causing bad wounds about the body. 4.00pm inoculated for cholera for second time.', null, null, null, true),
('Sunday', '1st', 'August', 'Attended a service. First Sunday at liberty for a long time.', null, null, null, true),
('Monday', '2nd', 'August', 'About teatime today the monitors (small warships with large guns) commenced a furious shelling of the left ridge of Achi Baba with high explosive shells.', null, null, null, true),
('Tuesday', '3rd', 'August', 'About the same time as yesterday the monitors began pumping shells at the hill causing a tremendous dust.', null, null, null, true),
('Wednesday', '4th', 'August', 'Third day about the same time as yesterday and Monday the monitors again started their shelling dropping a few in the Turkish trenches.', null, null, null, true),
('Thursday', '5th', 'August', 'First thing this morning a Taube came over dropping a few bombs and about 6.30pm returned with a few more bombs but didn’t do much damage. We are still waiting in camp for the big engagement to commence.', 'Taube - Germany’s first mass produced military aeroplane proved to be inferior as a serious warplane and soon replaced.', null, null, true),
('Friday', '6th', 'August', 'Everything very quiet today until about 3.30pm when the advanced Australian batteries assisted by the monitors started a big bombardment just outside Krithia and the Turks right flank soon after which our chaps made a charge taking one of two trenches the Turks * a * attack.', null, null, null, true),
('Saturday', '7th', 'August', 'The artillery * and battle lasted all night and keep it up all today all along the line. The air was simply alive with scream shells and shrapnel mingled with the whine of bullets. Evidently this is what we had been waiting for we were called out and were soon up to the eyes in it having a lucky escape from the start for the Turks spotted us coming up and greeted us with shrapnel luckily nobody hit. At it all night, about *.30am R Holden was killed with a bullet and Percy wounded * nearly blinded by shrapnel all in 3rd Field Ambulance.', null, null, null, true),
('Sunday', '8th', 'August', 'Early morning battle seemed to quieten down so we were withdrawn and returned to our dugouts.', null, null, null, true),
('Monday', '9th', 'August', 'Feeling a little stiff and sore after a busy weekend we turned in and had a good rest.  Evening – it is rumoured we are standing by to move for a fresh landing.', null, null, null, true),
('Tuesday', '10th', 'August', 'MY BIRTHDAY (he was 22). Put on fatigue being my duty on. Commenced day by a joy ride in a GS wagon down to stores. Didn’t half get a bumping over shell holes. Rest of day very quiet.', 'GS Wagon - General Service horse and wagon used to transport food, arms and equipment to the front.', null, null, true),
('Wednesday', '11th', 'August', 'Resting in camp later in the day. Annie from Asia is trying to find the artillery on * side dropped a few of her calling cards about the camp.', null, null, null, true),
('Thursday', '12th', 'August', 'Turks tried to break through our lines making a charge but were repulsed after about 20 mins.', null, null, null, true),
('Friday', '13th', 'August', 'Very slack today nothing much doing, wouldn’t think there was a war on.', null, null, null, true),
('Saturday', '14th', 'August', 'This morning the Turks commenced by sending a few shells into our camp but luckily nobody was in the dugouts that were hit. They quietened down however about midday.', null, null, null, true),
('Sunday', '15th', 'August', 'Attended a service.', null, null, null, false),
('Monday', '16th', 'August', 'Another attack expected warned to stand by to turn out.', null, null, null, true),
('Tuesday', '17th', 'August', 'Turned out at 5.30am and were sent on the left flank near Krithia. The attack not yet commenced.', null, null, null, true);
